### ISSUE TITLE
Underscores are inappropriately highlighted if it is in a word

### ISSUE THREAD

**Issue by xuhdev** [tpope/vim-markdown#21]
For example,

```
Hello_my

```

The following is the screenshot:

![](http://i.imgur.com/29LVA.png)

I don't think the red highlighting is correct. It means something wrong happens. I'm using the latest version from GitHub master branch.

**Comment by chmnoh** [comment]
If you just want to hide the error highlighting, consider below "dirty-hack":
```
syn match markdownError "\w\@<=\w\@="
```

**Comment by rococode** [comment]
Worth noting that this messes with MathJax (Latex for Markdown)

![](https://i.imgur.com/4zWVXJG.png)

You end up with underscores all over if you use subscripts and they can't be escaped (if escaped, MathJax renders them as actual underscores instead of switching to subscripts. Would be nice if the check could just be disabled somehow.

**Comment by zhyiyu** [comment]
> syn match markdownError "\w\@<=\w\@="

Hi, did you put this in this in `.vimrc`? I put it in `.vimrc` and it does not work.

**Comment by Frydac** [comment]
@zhyiyu 

Try to type it directly in your commandline and see if it works then. It probably will.
You need to make sure it comes later than e.g. loading your colorscheme, or the line 'syntax on' (syntax enable is better as it doesn't firs clear the syntax iirc). (I'm not sure about the exact best practices here.. so read about it in `:h syntax` for example)

**Comment by tpope** [comment]
Add `hi link markdownError NONE` to `after/syntax/markdown.vim`. That `syntax match` is nonsense.

**Comment by JohanChane** [comment]
add to .vimrc

```vim
autocmd BufWinEnter,FileType *.md syn match markdownError "\w\@<=\w\@="
```

**Comment by GianniGi** [comment]
> `syn match markdownError "\w\@<=\w\@="`

doesn't work

**Comment by midchildan** [comment]
Could this be reconsidered? With the way things are now, many people would have to choose between ignoring the error or personally enforcing everyone to escape underscores.

A quick investigation shows that [only 2 out of 28 implementations](https://babelmark.github.io/?text=foo_bar_baz) treat underscores in the middle of a word as an emphasis instead of a literal underscore. Of the 2, Pandoc only does so in an opt-in basis. GitHub generates READMEs for new repos without escaping underscores. Furthermore, [Prettier the formatter even removes the backslashes](https://github.com/prettier/prettier/issues/3728).

With tools including formatters working against escaping, out in the wild Markdown documents aren't going to escape underscores any time soon. The error seems unactionable at this point.

**Comment by midchildan** [comment]
As an aside, I now have the following fix in my configuration based on my somewhat suspect understanding of [`:h :syn-transparent`](https://vimhelp.org/syntax.txt.html#%3Asyn-transparent). It attempts to unhighlight unescaped underscores, but keep the highlighting of other errors that might get added in the future. The fix appears to be working.

```vim
syn match markdownIgnore "\w\@<=_\w\@=" transparent contains=NONE
syn cluster markdownInline add=markdownIgnore
```
