### ISSUE TITLE
Only the initial '>' is highlighted in blockquote

### ISSUE THREAD

**Issue by RichardDooling** [tpope/vim-markdown#47]
Not the rest of the text in the blockquote. I am guessing that his is being caused by some conflict I have in .vimrc or another plugin. I will investigate.

But does anyone else see this?

I'm using the latest MacVim and extension .markdown

**Comment by telemachus** [comment]
I was about to file this same bug. Can I ask why you prefer this (rather than highlighting the entire blockquote in some way)?

**Comment by tpope** [comment]
I no longer remember why, but my guess was concerns about implementing robustly. I would entertain a patch.

**Comment by telemachus** [comment]
Ok. I have something that works (just?), but I'll take a hard look at how robust it is and then submit a patch. Thanks.

**Comment by tpope** [comment]
To be clear, robustly means getting all lines when only the first is marked, as in the following:

```
> line 1
line 2
```

I do think I prefer highlighting the `>` only. But if you want to add the requisite highlight groups to hook into, go for it.

**Comment by telemachus** [comment]
What I have now is not that robust. With hard-wrapped text, vim will normally insert its own new `> ` after automatically producing `line 2` due to the length of `> line 1`. But if the user inserts their own carriage return (without adding `> `), then `line 2` is no longer considered part of the blockquote.

I understand that this isn't good enough. I'll work on it when I have time and submit a patch if I get it into sufficiently solid shape. Thanks for clarifying.

**Comment by tpope** [comment]
You can still add a highlight group without getting line 2 if you want as a hook. Just leave it transparent by default.
