### ISSUE TITLE
MACVIM does not show syntax highlight

### ISSUE THREAD

**Issue by tywtyw2002** [tpope/vim-markdown#55]
in macvim is does not show syntax highlight, but in vim is work fine.

see, this picture 
[this](http://ww2.sinaimg.cn/large/57d8aba6gw1ea8ww5cv5lj21700ycqav.jpg)
![pic](http://ww2.sinaimg.cn/large/57d8aba6gw1ea8ww5cv5lj21700ycqav.jpg)

**Comment by mikehagerty** [comment]
I just landed on this thread and though my symptoms were the same (no syntax highlighting), the reason is totally different.

I've used vi/vim forever and finally decided to upgrade from vim 7.3 to vim 8.1.

I downloaded Vim/MacVim as dmg from MacVim home.  This installs these into my Applications folder, eg:
/Applications/MacVim.app/Contents/MacOS/Vim

I had soft-linked this to be my std vi:
>ln -s /Applications/MacVim.app/Contents/MacOS/Vim /usr/bin/vi

but syntax highlighting didn't work ... until I read:
http://vimdoc.sourceforge.net/htmldoc/syntax.html

and set my VIMRUNTIME env to find the syntax dir:
>export VIMRUNTIME=/Applications/MacVim.app/Contents/Resources/vim/runtime

e.g., vim 8.1 looks for ${VIMRUNTIME}/syntax/syntax.vim

and now all works!
