### ISSUE TITLE
Multiline lists don't highlight correctly.

### ISSUE THREAD

**Issue by jszakmeister** [tpope/vim-markdown#81]
I have the following in a markdown file:

``` text
* A list

  - A list with a really long entry that spans multiple lines to show the
    error that I'm seeing.
```

It my case, I'm using two spaces for indentation, which means the start of the second line is on a 4 space boundary.  It then renders as code--which can be seen in the screenshot below.  I realize it's a painful use-case, but it would be nice to see it fixed.

<img width="777" alt="screen shot 2015-09-06 at 8 48 08 am" src="https://cloud.githubusercontent.com/assets/448087/9704426/3881dc32-5474-11e5-9c4b-032e08865efb.png">

**Comment by tpope** [comment]
And now you know the reason code blocks *aren't* highlighted by default.

**Comment by jszakmeister** [comment]
Heh, I see--I have this in my vimfiles:

```vim
    " Setup some extra highlighting for code blocks.  This matches the
    " highlighting from Ben William's syntax/mkd.vim and is a decent fallback
    " when we don't support the embedded language or the block is inline.
    highlight default link markdownCode                  String
    highlight default link markdownCodeBlock             String
```

So that's where the highlighting comes from.  But it'd still be nice to have it work correctly.  I guess I need to consider disabling the highlighting for now.

**Comment by 0cjs** [comment]
I'm having the same problem, and it's _really_ annoying me because I do a lot of meeting minutes in markdown where a substantial part of the document may be list continuation lines indended more than four spaces.

I figured out how to disable highlighting of code blocks (`highlight link markdownCodeBlock NONE`), but that also disables `_italic_`, `` `code` `` etc. markup in those blocks. Is there a way to turn off code block regions, e.g. by somehow undoing the `syn region markdownCodeBlock start="    \|\t" end="$" contained` command after it's been executed?
