### ISSUE TITLE
Underscores considered as syntax error

### ISSUE THREAD

**Issue by netei** [tpope/vim-markdown#85]
Hi, whenever I write : 

```
Hello foo_bar, how are you ?
```

The underscore in that sentence is highlighted as an error : 

See this screenshot 
![vim_markdown](https://cloud.githubusercontent.com/assets/13066384/10572406/804853c0-7648-11e5-96c6-c47e6fe1962e.PNG)

Is this expected ?

**Comment by delphinus35** [comment]
The strings surrounded by underscores will be converted to `<em>...</em>` HTML tag that indicates it is emphasized. So single underscore, you show above as an example, seems to be an error.

**Comment by netei** [comment]
It probably makes sense not to treat `_` as an error when the underscore is not behind a space

**Comment by delphinus35** [comment]
You can use `_` and `*` in middle of words. The original spec says,
http://daringfireball.net/projects/markdown/syntax#em
> Emphasis can be used in the middle of a word:
> > un*frigging*believable

**Comment by netei** [comment]
Still, it means I can't use underscores in word, when I snake_case identifiers, which is a bit saddenning

**Comment by delphinus35** [comment]
I think so, too. Just to make sure, the symbols `_`, `*` can be escaped by `\` such as `some\_snake\_case\_word`.

**Comment by tpope** [comment]
There's no such thing as an underscore in natural language. What you want is an inline code block, no two ways about it.

Different markdown engines have different tolerance levels for inline underscores. Many will screw you over with a giant block of emphasized text the second you use 2 in one paragraph. I flag them as errors because they *are* errors, even if some engines are more forgiving about them.
