### ISSUE TITLE
`:set spell` does not work on normal text but works on headers

### ISSUE THREAD

**Issue by scwood** [tpope/vim-markdown#89]
I am having this weird bug with spell checking, it's catching errors in headers just fine but not in normal text.

Disabling vim-markdown returns the desired behavior. 

![screen shot 2015-12-04 at 6 08 02 pm](https://cloud.githubusercontent.com/assets/9126138/11604998/00859cfe-9ab2-11e5-8fb3-97aae6c59828.png)

**Comment by tpope** [comment]
"Normal text' is highlighted as HTML, so my guess is things are broken on that end. I can confirm it works fine for me.

**Comment by scwood** [comment]
So this line seems to be causing the trouble. 

`let g:markdown_fenced_languages = ['java', 'python', 'javascript']`

With this minimal vimrc:
```
set nocompatible

call plug#begin()
Plug 'tpope/vim-markdown'
call plug#end()

let g:markdown_fenced_languages = ['java', 'python', 'javascript']
```

Getting rid of that line fixes the problem. Am I using that feature incorrectly?

**Comment by tpope** [comment]
You are using it correctly. However, many file types weren't designed for embedding and can have issues, particularly when you embed multiple at the same time and they have the chance to interact with each other. It's the reason no fenced languages are enabled by default.

It's *possible* that adding the correct `syn spell` declaration to `syntax/markdown.vim` would take precedence and solve this issue. If you find something that works, send a pull request. Otherwise, I'm going to assume this is unfixable.

**Comment by natebosch** [comment]
Adding `syntax spell toplevel` after the loop around `g:markdown_fenced_languages` resolves the issue for me, but I'm pretty much shooting in the dark so I don't know if that will break anyone else.

I narrowed it down to the syntax for 'java'. If I remove that from my markdown_fenced_languages then everything works fine.
